import { StyleSheet } from "react-native";
import { AppTheme } from "@/constants/app-theme";

export const styles = StyleSheet.create({
  contentMinimal: {
    paddingVertical: 20,
    paddingHorizontal: 12,
    alignItems: "center",
  },
  container: {
    width: "100%",
    maxWidth: 860,
  },
  title: {
    fontSize: 22,
    color: AppTheme.colors.text,
    fontFamily: AppTheme.typography.fontBold,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    color: "#6F7480",
    fontFamily: AppTheme.typography.fontRegular,
    marginBottom: 24,
  },
  progressCard: {
    borderWidth: 1,
    borderColor: "#F5F5F5",
    borderRadius: 20,
    backgroundColor: "#F5F5F5",
    paddingHorizontal: 20,
    paddingVertical: 18,
    marginBottom: 18,
    marginTop: 18,
  },
  progressHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  progressStep: {
    flex: 1,
    position: "relative",
    alignItems: "flex-start",
  },
  progressDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E4E1E8",
    marginBottom: 8,
    zIndex: 1,
  },
  progressDotDone: {
    backgroundColor: "#077755",
  },
  progressDotCurrent: {
    backgroundColor: AppTheme.colors.primary,
  },
  progressDotText: {
    fontSize: 13,
    color: "#6F7480",
    fontFamily: AppTheme.typography.fontBold,
  },
  progressDotTextCurrent: {
    color: "#FFFFFF",
  },
  progressLabel: {
    fontSize: 13,
    color: "#6F7480",
    fontFamily: AppTheme.typography.fontBold,
  },
  progressLabelCurrent: {
    color: AppTheme.colors.text,
  },
  progressLine: {
    position: "absolute",
    top: 14,
    left: 36,
    right: 12,
    height: 1,
    backgroundColor: "#D8D2DD",
  },
  progressDescription: {
    fontSize: 13,
    lineHeight: 19,
    color: "#6F7480",
    fontFamily: AppTheme.typography.fontRegular,
  },
  formContainer: {
    borderWidth: 1,
    borderColor: "#F5F5F5",
    borderRadius: 20,
    backgroundColor: "#F5F5F5",
    padding: 24,
  },
  formHeader: {
    marginBottom: 20,
  },
  formTitle: {
    fontSize: 20,
    color: AppTheme.colors.text,
    fontFamily: AppTheme.typography.fontBold,
    marginBottom: 6,
  },
  formSubtitle: {
    fontSize: 14,
    lineHeight: 21,
    color: "#6F7480",
    fontFamily: AppTheme.typography.fontRegular,
  },
  ownerBlock: {
    borderWidth: 1,
    borderColor: "#EEE8F2",
    borderRadius: 16,
    backgroundColor: "#F5F5F5",
    padding: 16,
    marginBottom: 16,
  },
  ownerHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    marginBottom: 14,
  },
  ownerTitle: {
    fontSize: 15,
    color: AppTheme.colors.text,
    fontFamily: AppTheme.typography.fontBold,
  },
  removeButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#F1D1D1",
    backgroundColor: "#FFF7F7",
  },
  removeButtonText: {
    fontSize: 13,
    color: "#A22C2C",
    fontFamily: AppTheme.typography.fontBold,
  },
  fieldSpacing: {
    marginBottom: 16,
  },
  fieldSpacingLast: {
    marginBottom: 0,
  },
  fieldRow: {
    flexDirection: "row",
    gap: 16,
  },
  fieldHalf: {
    flex: 1,
  },
  addButton: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: "#D8B8E1",
    borderRadius: 14,
    borderStyle: "dashed",
    backgroundColor: "#F5F5F5",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  addButtonText: {
    fontSize: 15,
    color: AppTheme.colors.primary,
    fontFamily: AppTheme.typography.fontBold,
  },
  actionsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 24,
  },
  selectLabel: {
    color: AppTheme.colors.text,
    fontSize: 15,
    fontFamily: AppTheme.typography.fontBold,
    marginBottom: 8,
  },
  selectTrigger: {
    minHeight: 52,
    borderWidth: 1.5,
    borderColor: AppTheme.colors.inputBorder,
    borderRadius: 16,
    backgroundColor: "#F5F5F5",
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  selectValue: {
    flex: 1,
    color: AppTheme.colors.text,
    fontSize: 15,
    fontFamily: AppTheme.typography.fontRegular,
  },
  selectPlaceholder: {
    color: "#A9A9A9",
  },
  optionsContainer: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#D3D3D3",
    borderRadius: 16,
    backgroundColor: "#F5F5F5",
    overflow: "hidden",
  },
  optionItem: {
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  optionItemPressed: {
    backgroundColor: "#F3F0F6",
  },
  optionText: {
    color: AppTheme.colors.text,
    fontSize: 14,
    fontFamily: AppTheme.typography.fontRegular,
  },
  spouseBlock: {
    borderWidth: 1,
    borderColor: "#D8D2DD",
    borderRadius: 14,
    backgroundColor: "#F5F5F5",
    padding: 14,
  },
  spouseTitle: {
    color: AppTheme.colors.text,
    fontSize: 14,
    fontFamily: AppTheme.typography.fontBold,
    marginBottom: 14,
  },
  doubleColumn: {
    flexDirection: "row",
    gap: 16,
  },
  flexField: {
    flex: 1,
  },
  fieldShort: {
    width: 220,
  },
  helperBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    borderWidth: 1,
    borderColor: "#E7DFEC",
    borderRadius: 14,
    backgroundColor: "#F5F5F5",
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 16,
  },
  helperText: {
    flex: 1,
    color: "#6F7480",
    fontSize: 13,
    lineHeight: 19,
    fontFamily: AppTheme.typography.fontRegular,
  },
  divider: {
    height: 1,
    backgroundColor: "#E7DFEC",
    marginVertical: 4,
  },
  sectionTitle: {
    marginTop: 16,
    marginBottom: 14,
    fontSize: 16,
    color: AppTheme.colors.text,
    fontFamily: AppTheme.typography.fontBold,
  },
  successCard: {
    borderWidth: 1,
    borderColor: "#E7DFEC",
    borderRadius: 20,
    backgroundColor: "#F5F5F5",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingVertical: 36,
  },
  successIcon: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#077755",
    marginBottom: 18,
  },
  successTitle: {
    fontSize: 22,
    color: AppTheme.colors.text,
    fontFamily: AppTheme.typography.fontBold,
    textAlign: "center",
    marginBottom: 8,
  },
  successText: {
    maxWidth: 520,
    fontSize: 15,
    lineHeight: 22,
    color: "#6F7480",
    fontFamily: AppTheme.typography.fontRegular,
    textAlign: "center",
  },
  successActions: {
    marginTop: 24,
  },
});
